version: '3'
services:

  # MySQL service
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: GestionLocal
    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  # Spring Boot service
  springboot-app:
    image: azyzbc/integratedprojects:1.0.3
    ports:
      - "8087:8087"
    depends_on:
      - mysql
    environment:
      SPRING_APPLICATION_JSON: >-
        {
          "spring.datasource.url": "jdbc:mysql://mysql:3306/GestionLocal?createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }
      tty: true
  # Angular app service
  angular-app:
    image: zakariabensalem98/pi:angular2
    ports:
      - "4200:80"
    depends_on:
      - springboot-app

volumes:
  mysql-data:
